# 03_train_case_yolo.py
# -*- coding: utf-8 -*-
"""
Train YOLO on the converted "case_yolo" dataset.

Input:
  output/case_yolo/data.yaml   (generated by 01_dataset_convert_case_to_yolo.py)

Output (default):
  runs/detect/case_yolo_train/weights/best.pt
  runs/detect/case_yolo_train/weights/last.pt
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from ultralytics import YOLO


# ✅ 让脚本在任何目录运行都能 import scripts.intelligence_class._utils.pathing
_this = Path(__file__).resolve()
for p in [_this] + list(_this.parents):
    if (p / "data").exists() and (p / "scripts").exists():
        sys.path.insert(0, str(p))
        break

from scripts.intelligence_class._utils.pathing import find_project_root
try:
    from scripts.intelligence_class._utils.pathing import resolve_under_project  # type: ignore
except Exception:  # pragma: no cover
    resolve_under_project = None  # type: ignore


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", type=str, default="output/case_yolo/data.yaml",
                        help="dataset yaml (relative to project root)")
    parser.add_argument("--model", type=str, default="yolo11s.pt",
                        help="base model weight (relative to project root), e.g. yolo11n.pt/yolo11s.pt")
    parser.add_argument("--epochs", type=int, default=80)
    parser.add_argument("--imgsz", type=int, default=832)
    parser.add_argument("--batch", type=int, default=8)
    parser.add_argument("--device", type=str, default="0", help="0 / 0,1 / cpu")
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--project", type=str, default="runs/detect")
    parser.add_argument("--name", type=str, default="case_yolo_train")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--patience", type=int, default=30)
    parser.add_argument("--cache", type=int, default=0, help="1=cache images in RAM (may explode memory)")
    parser.add_argument("--resume", type=int, default=0, help="1=resume from last run")
    args = parser.parse_args()

    current_file = Path(__file__).resolve()
    project_root = find_project_root(current_file)

    # ✅ 路径解析统一：支持用户传绝对路径；相对路径统一相对 project_root
    if resolve_under_project is not None:
        data_yaml = resolve_under_project(project_root, args.data)
        model_path = resolve_under_project(project_root, args.model)
        runs_dir = resolve_under_project(project_root, args.project)
    else:
        # fallback: 如果你的 pathing.py 没有 resolve_under_project
        def _resolve(p: str) -> Path:
            pp = Path(p)
            return pp.resolve() if pp.is_absolute() else (project_root / pp).resolve()

        data_yaml = _resolve(args.data)
        model_path = _resolve(args.model)
        runs_dir = _resolve(args.project)

    if not data_yaml.exists():
        raise FileNotFoundError(f"data.yaml not found: {data_yaml}")
    if not model_path.exists():
        raise FileNotFoundError(f"model weight not found: {model_path}")

    yolo = YOLO(str(model_path))

    yolo.train(
        data=str(data_yaml),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        workers=args.workers,
        project=str(runs_dir),
        name=args.name,
        seed=args.seed,
        patience=args.patience,
        cache=bool(int(args.cache)),
        resume=bool(int(args.resume)),
        # 常用增强/训练参数你也可以后续加：lr0, lrf, hsv_h, hsv_s, etc.
    )

    # 训练结束后的 best.pt 默认会在：
    # runs/detect/<name>/weights/best.pt


if __name__ == "__main__":
    main()
